from django.conf import settings

XTERM_MAX_READ_BYTES = 1024 * 20
XTERM_MAX_CON = settings.MAX_WS_CONNECTION_PER_MODULE
XTERM_CONNECTION_LIMIT_CODE = 4000
XTERM_USER_AUTH_FAIL_CODE = 4002

RUNPROCESS_CON_CACHE_KEY = "run_process_ws_con"
REDIS_LOCK_PREFIX = "_lock_"

JSON_TYPE = "0"
TYPE_PTY_INPUT = 0
TYPE_PTY_OUTPUT = 1
TYPE_RESIZE = 2
TYPE_INIT = 3
TYPE_EXITED = 4
TYPE_ERROR = 5

JSON_CONTENT = "1"

JOURNALCTL = 0