XTERM_MAX_READ_BYTES = 1024 * 20
XTERM_MAX_CONNECTION = 1
XTERM_CONNECTION_LIMIT_CODE = 4000
XTERM_USER_AUTH_FAIL_CODE = 4002

JSON_TYPE = "0"
TYPE_PTY_INPUT = 0
TYPE_PTY_OUTPUT = 1
TYPE_RESIZE = 2
TYPE_INIT = 3
TYPE_EXITED = 4
TYPE_ERROR = 5

JSON_CONTENT = "1"

JOURNALCTL = 0