DATA_TYPE = 0

LIST_FILE = 0
CREATE_FILE = 1
DELETE_FILE = 2
COPY_FILE = 3
MOVE_FILE = 4
DIR_SIZE = 5
MAKE_DIR = 6
CANCEL_DIR_SIZE = 7

DATA_ARGS = 1

# ALL_FUNCTIONS = [LIST_FILE, CREATE_FILE, DELETE_FILE, COPY_FILE, MOVE_FILE, COPY_DIR,
#                  MAKE_DIR, DELETE_DIR]
