DATA_TYPE = 0

LIST_FILE = 0
CREATE_FILE = 1
DELETE_FILE = 2
COPY_FILE = 3
MOVE_FILE = 4
# COPY_DIR = 5
MAKE_DIR = 6
# DELETE_DIR = 7
ERROR_CODE = 20

DATA_ARGS = 1


# ALL_FUNCTIONS = [LIST_FILE, CREATE_FILE, DELETE_FILE, COPY_FILE, MOVE_FILE, COPY_DIR,
#                  MAKE_DIR, DELETE_DIR]
