DATA_TYPE = 0

LIST_FILE = 0
LIST_ROOT_FILE = 1
CREATE_FILE = 2
DELETE_FILE = 3
COPY_FILE = 4
MOVE_FILE = 5
COPY_DIR = 6
MAKE_DIR = 7
DELETE_DIR = 8

DATA_ARGS = 1

ALL_FUNCTIONS = [LIST_FILE, LIST_ROOT_FILE, CREATE_FILE, DELETE_FILE, COPY_FILE, MOVE_FILE, COPY_DIR,
                 MAKE_DIR, DELETE_DIR]
